#ifndef MODBUSMASTER_GLOBAL_H
#define MODBUSMASTER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MODBUSMASTER_LIBRARY)
#  define MODBUSMASTERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MODBUSMASTERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MODBUSMASTER_GLOBAL_H
